import * as vscode from 'vscode';
import OctokitClient from './oktokit';

export function activate(context: vscode.ExtensionContext) {

  // Register the "Create Gist" command
  let disposable = vscode.commands.registerCommand('gist-uploader.createGist', async () => {

    // Get the active text editor
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      vscode.window.showErrorMessage("No active text editor found");
      return;
    }

    // Get the highlighted text or the entire file contents
    let highlightedText = editor.document.getText(); // Default to entire file if selection not given
    const selection = editor.selection;
    if (!selection.isEmpty) {
      highlightedText = editor.document.getText(selection);
    }

    // Get the Personal Access Token from the configuration
    const config = vscode.workspace.getConfiguration('gist-uploader');
    const pat: String = config.get('githubPAT') || "";
    const octokitClient = new OctokitClient(pat);

    // Check if the Personal Access Token is given
    if (pat === "") {
      vscode.window.showErrorMessage(`No GitHub Personal Access Token given`);
      return;
    }

    // Create the Gist and copy the URL to the clipboard
    try {
      const gist = await octokitClient.createGist(
        highlightedText,
        "Autogenerated from VSCode",
        true);
      vscode.env.clipboard.writeText(gist.html_url);
      vscode.window.showInformationMessage(`Gist created: ${gist.html_url} (URL copied to clipboard)`);
    } catch (error) {
      vscode.window.showErrorMessage(`Error creating Gist`);
    }
  });

  // Add the "Create Gist" option to the context menu
  context.subscriptions.push(disposable);
  context.subscriptions.push(vscode.commands.registerTextEditorCommand('gist-uploader.addCreateGistOptionToContextMenu', (textEditor: vscode.TextEditor, textEditorEdit: vscode.TextEditorEdit, ...args: any[]) => {
    const selectedText = textEditor.document.getText(textEditor.selection);
    if (selectedText) {
      vscode.window.showTextDocument(textEditor.document).then(() => {
        vscode.commands.executeCommand('editor.action.showContextMenu', {
          getActions: () => [
            {
              label: 'Create Gist',
              command: 'gist-uploader.createGist',
              arguments: [selectedText]
            }
          ]
        });
      });
    }
  }));
}

export function deactivate() {}
